filter:
    excluded_paths:
        - tests/*
        - node_modules/*
        - bower_components/*
        - vendor/*
        - storage/*
        - resources/*
        - public/*
        - docs/*
        - database/*
