language: php

php:
    - 5.5

matrix:
    fast_finish: true

before_script:
    - phpenv config-add .travis.config.ini
    # - phpenv config-rm xdebug.ini

    - composer self-update
    - composer install --prefer-source --no-interaction --dev

    # - chmod -R 777 app/storage/

script:
    # - phpunit --testsuite=Unit --coverage-clover tests/clover-unit.xml
    - phpunit --testsuite=Functional --coverage-clover tests/clover-functional.xml

after-script:
    - php vendor/bin/coveralls -v

after_failure:
    # - cat app/storage/logs/laravel.log
    # - cat tests/_output/*